make: test

test: test.py
	python -B test.py

ms: ms.py
	python -B ms.py

rlist: rlist.py
	python -B rlist.py

array_printer: array_printer.py
	python -B array_printer.py

clean:
	rm *.pyc ../lists-py.txt
